### ISSUE TITLE
Unable to locate credentials

### ISSUE THREAD

**Issue by cardtap** [mariamrf/py-lambda-action#14]
Hi there, I read the "closed" issue but I am relatively sure I do not have a type. I've copied over the AWS_ACCESS_KEY_ID and key multiple times, and made sure the secrets exist in the "Actions" environment. Do you have any ideas?
My code copied over directly:
```
env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'
```
And the env variable/secrets:
```
AWS_SECRET_ACCESS_KEY Updated 6 minutes ago
AWS_ACCESS_KEY_ID Updated 7 minutes ago
```
The error after build (but it says it succeeded):
```
Unable to locate credentials. You can configure credentials by running "aws configure".
Using the layer in the function...
Unable to locate credentials. You can configure credentials by running "aws configure".
```

I temporarily placed throwaway IAM credentials directly in the main.yml file and the build succeeded in updating the lambda function, but not when the keys are in secrets...

Thank you for any ideas you might have!
